### ISSUE TITLE
显示文件损坏，明明正版可以正常启动

### ISSUE THREAD

**Issue by liveskai** [R2NorthstarCN/R2NorthstarCN_Launcher#1]
![image](https://user-images.githubusercontent.com/54350655/147409381-b47ed166-7f68-4a9b-9ad9-a883f7ad2a57.png)

**Comment by evokra** [comment]
重装Origin，游戏是没有问题的

**Comment by wing42** [comment]
这个情况我也有遇到过，或者说是每次都会遇到。我的解决方法就是在Northstar开始走代码之后点击文件夹里的Titanfall2.exe，这样就能成功启动。虽然比较玄学，但是这种方法我是每次都可以成功启动的……另外建议启动Northstar之前先手动启动Origin。

**Comment by D3-3109** [comment]
太老的问题，现在wiki内已经写了该问题的解决方法，故关闭该Issue
