### ISSUE TITLE
页面没了

### ISSUE THREAD

**Issue by liveskai** [R2NorthstarCN/R2NorthstarCN_Launcher#12]
![image](https://user-images.githubusercontent.com/54350655/207860812-4b6ac17b-eb7f-467d-bed0-ed151cdfb4cc.png)
![image](https://user-images.githubusercontent.com/54350655/207860840-d9aefb87-9fc2-4f96-aaeb-d62b912ee2d6.png)

**Comment by D3-3109** [comment]
MD很久没更新了，现在NSCN的WIKI站是https://wiki.northstar.cool
