### ISSUE TITLE
能进主页面，点进入北极星就会报错

### ISSUE THREAD

**Issue by Yootoyo** [R2NorthstarCN/R2NorthstarCN_Launcher#13]
![202301-07151940](https://user-images.githubusercontent.com/77391076/211139159-43dbcfd1-caab-4879-8466-79b970e43b43.png)

一直提示这个文件有问题

**Comment by D3-3109** [comment]
更新方式导致的有文件未被覆盖的问题，解决方法是直接删除R2Northstar文件夹重新安装NSCN即可
