### ISSUE TITLE
启动北极星报错

### ISSUE THREAD

**Issue by ander4456** [R2NorthstarCN/R2NorthstarCN_Launcher#15]
如图，启动北极星后报错
![image](https://user-images.githubusercontent.com/132671374/236456156-8f46533c-2fc8-4dea-a511-82af863fddc8.png)
下图为命令行截图
![image](https://user-images.githubusercontent.com/132671374/236456502-e2d00c82-c7c6-495a-a320-6bb64029857a.png)
版本为1.13.5

**Comment by D3-3109** [comment]
看前几个issue，已经给出解决方法
