### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by alt-0191** [R2NorthstarCN/R2NorthstarCN_Launcher#2]
![图片](https://user-images.githubusercontent.com/56725325/147639342-8180c6f0-05c0-482a-96a0-79e5094663a9.png)
[nsdump29-12-2021 15-50-30.zip](https://github.com/R2NorthstarCN/R2NorthstarCN_Launcher/files/7787812/nsdump29-12-2021.15-50-30.zip)

**Comment by D3-3109** [comment]
远古问题，故关闭Issue
