### ISSUE TITLE
BUG:: Write persistence failed for user

### ISSUE THREAD

**Issue by Miaoyww** [R2NorthstarCN/R2NorthstarCN_Launcher#20]
### BUG 描述
无法连接至任意服务器

### 复现流程
在问题出现之前，我的启动器版本是1.15.8且无任何问题
在1/7，更新至1.16.3之后，尝试打开任意服务器出现连接超时，查看日志如此:
[17:47:42] [NORTHSTAR] [errr] [Pdata] Write persistence failed for user: 1009485454540, error: Success (no error)

### 设备信息:
 - OS: Windows 11 23H2
 - NS版本: 1.16.3
 - 游戏平台: Steam

### 日志文件
稍后补传

**Comment by Miaoyww** [comment]
[nslog2024-01-07 18-02-40.txt](https://github.com/R2NorthstarCN/R2NorthstarCN_Launcher/files/13852907/nslog2024-01-07.18-02-40.txt)

**Comment by Miaoyww** [comment]
![image](https://github.com/R2NorthstarCN/R2NorthstarCN_Launcher/assets/52089819/fed53188-7fb4-441a-a280-467b4214e1ad)
已自行解决

**Comment by fatelove42** [comment]
好好好
