### ISSUE TITLE
BUG:: 进入游戏不是游玩界面而是一个控制台，背景是游玩界面的cg

### ISSUE THREAD

**Issue by JadeGreened** [R2NorthstarCN/R2NorthstarCN_Launcher#22]
### BUG 描述
进入游戏不是游玩界面而是一个控制台，背景是游玩界面的cg

### 复现流程
在发生问题前，我进行了如下操作:
1.将新版本的启动器解压到了游戏的路径

### 问题截图
我分了个屏幕，所以可能看着比较奇怪。  
![image](https://github.com/user-attachments/assets/d827b0c6-602d-4ce4-b903-068f73a6aaac)

### 设备信息:
 - OS: win10专业版19045.5011
 - NS版本: [例如: v1.77.7]

 - 游戏平台: EA

### 日志文件  
[nslog2024-10-23 22-53-21.txt](https://github.com/user-attachments/files/17494216/nslog2024-10-23.22-53-21.txt)

[nslog2024-10-23 22-30-55.txt](https://github.com/user-attachments/files/17494208/nslog2024-10-23.22-30-55.txt)

[nslog2024-10-23 22-29-12.txt](https://github.com/user-attachments/files/17494204/nslog2024-10-23.22-29-12.txt)

[nslog2024-10-23 22-24-36.txt](https://github.com/user-attachments/files/17494202/nslog2024-10-23.22-24-36.txt)

[nslog2024-10-23 22-23-52.txt](https://github.com/user-attachments/files/17494200/nslog2024-10-23.22-23-52.txt)

抽空看看吧哥，幸苦捏。

**Comment by wolf109909** [comment]
删除R2Northstar文件夹，重新安装北极星CN最新版本
