### ISSUE TITLE
BUG:: 更新1.17后无法启动北极星

### ISSUE THREAD

**Issue by yangyupian** [R2NorthstarCN/R2NorthstarCN_Launcher#23]
### BUG 描述
北极星版本从1.16更新到1.17后就无法启动北极星，1.17之前版本都能正常启动

### 复现流程
无论用指北针重装还是自己解压重装北极星新版本都报错，验证游戏完整性后重装北极星也报错

### 问题截图
![{6 OY642E_A5T YH@WEUEPE](https://github.com/user-attachments/assets/28acd04f-0a10-4da2-ab8d-bf2e735247a3)

![R ~BQ7ZRX1 7A`A)%S}48@2](https://github.com/user-attachments/assets/6d4e053d-4570-4141-9bac-e487f3d32b1a)

### 设备信息:
版本	Windows 10 专业版
版本号	22H2
操作系统内部版本	19045.5011
体验	Windows Feature Experience Pack 1000.19060.1000.0

**Comment by wolf109909** [comment]
目前有两例该问题，后续有解决方案会在这个issue下更新

**Comment by yangyupian** [comment]
> 目前有两例该问题，后续有解决方案会在这个issue下更新

好的好的，感谢，我还以为我要成为孤例了

**Comment by yangyupian** [comment]
更新1.18后可以正常启动了
