### ISSUE TITLE
Northstar has crashed北极星运行出错误

### ISSUE THREAD

**Issue by MoYouHun** [R2NorthstarCN/R2NorthstarCN_Launcher#5]
![NHC](https://user-images.githubusercontent.com/102510958/160748627-4ed61bb1-990e-4d4d-9e10-c2fb34fda34f.png)
![aa](https://user-images.githubusercontent.com/102510958/160748729-4dd88d0c-1488-4deb-9df6-cd6abfdac2e5.png)
更新之后就变成这样,打开会显示错误，然后直接跳到橘子平台

**Comment by Yizhouuu** [comment]
我也是同样问题，正在寻找解决办法

**Comment by D3-3109** [comment]
远古问题，故关闭该 Issue
