### ISSUE TITLE
从主菜单进入北极星服务器页面途中报错，文件被多次打开

### ISSUE THREAD

**Issue by HikariXP** [R2NorthstarCN/R2NorthstarCN_Launcher#6]
![微信图片_20220812131312](https://user-images.githubusercontent.com/49966455/184289198-2f320229-ccd2-4cd1-a0de-7516a2efedd6.jpg)

随后游戏闪退

**Comment by wasaibi12345** [comment]
我也有这个问题

**Comment by D3-3109** [comment]
更新方式导致的有文件未被覆盖的问题，解决方法是直接删除R2Northstar文件夹重新安装NSCN即可
