### ISSUE TITLE
进入服务器报错退出

### ISSUE THREAD

**Issue by linsnowmm** [R2NorthstarCN/R2NorthstarCN_Launcher#7]
![$~9TK53U31DG5R(J QU~U~D](https://user-images.githubusercontent.com/97744559/184354425-24b8520f-c462-499c-b201-ed0c76a6cfdd.png)

**Comment by wasaibi12345** [comment]
我也有这个问题

**Comment by Yootoyo** [comment]
我也是，请问解决了吗？

**Comment by D3-3109** [comment]
更新方式导致的有文件未被覆盖的问题，解决方法是直接删除R2Northstar文件夹重新安装NSCN即可
