### ISSUE TITLE
PLAYER_NOT_FOUND找不到玩家

### ISSUE THREAD

**Issue by Q78KG** [R2NorthstarCN/R2NorthstarCN_Launcher#9]
**BUG 描述**
PLAYER_NOT_FOUND找不到玩家

**复现流程**
在发生问题前，我进行了如下操作:
1. 进入游戏
2. 报错
**问题截图**
如果您
![屏幕截图(14)](https://user-images.githubusercontent.com/99022886/191257673-b4fa5cc8-ab4c-4442-8d00-867e677ad29e.png)

有截图，请将其粘贴在此处

**设备信息:**
 - OS:Windows11专业版
 - NS版本: [例如: v1.9.4]
 - 游戏平台:Steam

**日志文件**
请上传您的日志文件以便于我们分析
[nslog2022-09-20 20-21-32.txt](https://github.com/R2NorthstarCN/R2NorthstarCN_Launcher/files/9607555/nslog2022-09-20.20-21-32.txt)

**Comment by wolf109909** [comment]
请先更新到1.9.6再试

**Comment by Q78KG** [comment]
我已经是1.9.6了

**Comment by wolf109909** [comment]
橘子是否正确登录，并且没有封号历史？

**Comment by Q78KG** [comment]
正在封着

**Comment by wolf109909** [comment]
那是登不上的

**Comment by Q78KG** [comment]
我真的会谢，烂橘子无缘无故给我封了，垃圾客服不听我解释。唉，无语了
